---
name: "Tests"

on:
  push:
    branches-ignore:
      - "master"

jobs:
  gh_tests:
    runs-on: "ubuntu-latest"
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:

      - uses: "actions/checkout@v2"
        with:
          lfs: true
          fetch-depth: 0

      - name: "Retrieve the short SHA"
        id: "sha"
        run: echo "::set-output name=value::$(echo ${GITHUB_SHA::8})"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v1"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v1"

      - name: "Publish to GitHub Packages"
        uses: "docker/build-push-action@v2"
        with:
          context: .
          file: "./Dockerfile"
          platforms: "linux/amd64"
          load: true
          tags: |
            ghcr.io/marvinpinto/aws-kubectl:latest
            ghcr.io/marvinpinto/aws-kubectl:${{ steps.sha.outputs.value }}
